steps:
# Build base stage
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '--target', 'base',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:base',
    '.'
  ]

# Build deploy stage as latest
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '--target', 'deploy',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:latest',
    '.'
  ]

# Push base image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:base']

# Push latest image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:latest']

# If _RELEASE is set, tag latest as release and push
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "${_RELEASE}" == "true" ]]; then
      docker tag us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:latest us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:release
      docker push us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:release
    fi

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:base'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mabuhive/mabuhive:release'

substitutions:
  _RELEASE: 'false'  # Set to 'true' to also build and push release tag