steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/mabuhive:latest',
    '.'
  ]
images: ['gcr.io/$PROJECT_ID/mabuhive:latest']
